---
all:
  children:
    servers:
      children:
        local:
          children:
            ubuntu:
              children:
                application:
                  hosts:
                    app-server:
                      ansible_host: 3.90.11.111
                # database:
                #   hosts:
                #     database-server:
                #       ansible_host: 3.90.11.111
                # bastion:
                #   hosts:
                #     bastion-server:
                #       ansible_host: 3.90.11.111
                monitoring:
                  hosts:
                    monitoring-server:
                      ansible_host: 35.173.221.2
 